FROM alpine:3.8
#
COPY deploy /usr/local/deploy
COPY entrypoint.sh /usr/local/bin
RUN chown -R root:root /usr/local/deploy && \
    chmod -R 750 /usr/local/deploy && \
    chmod 750 /usr/local/deploy
#
EXPOSE 9999
USER 1001
WORKDIR /usr/local/deploy
ENTRYPOINT ["entrypoint.sh"]



